USE [master]
GO

/****** Object:  Database [PizzAltero_DataBase]    Script Date: 25.04.2024 4:26:06 ******/
CREATE DATABASE [PizzAltero_DataBase]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PizzAltero_DataBase', FILENAME = N'D:\SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\PizzAltero_DataBase.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PizzAltero_DataBase_log', FILENAME = N'D:\SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\PizzAltero_DataBase_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PizzAltero_DataBase].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PizzAltero_DataBase] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PizzAltero_DataBase] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PizzAltero_DataBase] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PizzAltero_DataBase] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PizzAltero_DataBase] SET ARITHABORT OFF 
GO

ALTER DATABASE [PizzAltero_DataBase] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [PizzAltero_DataBase] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PizzAltero_DataBase] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PizzAltero_DataBase] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PizzAltero_DataBase] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PizzAltero_DataBase] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PizzAltero_DataBase] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PizzAltero_DataBase] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PizzAltero_DataBase] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PizzAltero_DataBase] SET  DISABLE_BROKER 
GO

ALTER DATABASE [PizzAltero_DataBase] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PizzAltero_DataBase] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PizzAltero_DataBase] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PizzAltero_DataBase] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PizzAltero_DataBase] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PizzAltero_DataBase] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [PizzAltero_DataBase] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PizzAltero_DataBase] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [PizzAltero_DataBase] SET  MULTI_USER 
GO

ALTER DATABASE [PizzAltero_DataBase] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PizzAltero_DataBase] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PizzAltero_DataBase] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PizzAltero_DataBase] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [PizzAltero_DataBase] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [PizzAltero_DataBase] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [PizzAltero_DataBase] SET QUERY_STORE = ON
GO

ALTER DATABASE [PizzAltero_DataBase] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [PizzAltero_DataBase] SET  READ_WRITE 
GO

